<a href="https://colab.research.google.com/github/mohamedEmad23/Colab_Projects/blob/main/AML_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Uncomment the line below for reproducibility of results
# np.random.seed(0)

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Input dataset representing XOR operation
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
expected_output = np.array([[0], [1], [1], [0]])

# Hyperparameters
epochs = 10000  # Number of training iterations
lr = 0.1  # Learning rate
inputLayerNeurons, hiddenLayerNeurons, outputLayerNeurons = 2, 2, 1  # Number of neurons in each layer

# Randomly initializing weights and biases
hidden_weights = np.random.uniform(size=(inputLayerNeurons, hiddenLayerNeurons))
hidden_bias = np.random.uniform(size=(1, hiddenLayerNeurons))
output_weights = np.random.uniform(size=(hiddenLayerNeurons, outputLayerNeurons))
output_bias = np.random.uniform(size=(1, outputLayerNeurons))

# Display initial weights and biases
print("Initial hidden weights: ", end='')
print(*hidden_weights)
print("Initial hidden biases: ", end='')
print(*hidden_bias)
print("Initial output weights: ", end='')
print(*output_weights)
print("Initial output biases: ", end='')
print(*output_bias)

# Training the neural network
for _ in range(epochs):
    # Forward propagation
    hidden_layer_activation = np.dot(inputs, hidden_weights) + hidden_bias
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, output_weights) + output_bias
    predicted_output = sigmoid(output_layer_activation)

    # Compute error
    error = expected_output - predicted_output

    # Backpropagation
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    output_weights += hidden_layer_output.T.dot(d_predicted_output) * lr
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * lr
    hidden_weights += inputs.T.dot(d_hidden_layer) * lr
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * lr

# Display final weights and biases after training
print("Final hidden weights: ", end='')
print(*hidden_weights)
print("Final hidden bias: ", end='')
print(*hidden_bias)
print("Final output weights: ", end='')
print(*output_weights)
print("Final output bias: ", end='')
print(*output_bias)

# Display final output
print("\nOutput from neural network after 10,000 epochs: ", end='')
print(*predicted_output)


Initial hidden weights: [0.49004578 0.71287911] [0.71790646 0.39790338]
Initial hidden biases: [0.15481033 0.3088679 ]
Initial output weights: [0.39544443] [0.00579538]
Initial output biases: [0.40028992]
Final hidden weights: [5.83062615 3.70671585] [5.77545059 3.69557603]
Final hidden bias: [-2.4256205 -5.6693017]
Final output weights: [7.49076295] [-8.14339169]
Final output bias: [-3.36759088]

Output from neural network after 10,000 epochs: [0.05803383] [0.94663273] [0.94680608] [0.05744897]


In [ ]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()

# Splitting into train and test datasets
from sklearn.model_selection import train_test_split
datasets = train_test_split(iris.data, iris.target,
                            test_size=0.2)

# Assign train and test data
train_data, test_data, train_labels, test_labels = datasets

# Scaling the data using StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit the scaler on the train data
scaler.fit(train_data)

# Transform train and test data
train_data = scaler.transform(train_data)
test_data = scaler.transform(test_data)

# Print first three scaled training samples
print(train_data[:3])


[[-0.35954025 -1.47075021  0.01090463 -0.24500981]
 [ 0.13074191 -0.17302944  0.29537311  0.40545871]
 [ 0.25331245  0.69211775  0.46605419  0.53555241]]


In [ ]:
# Training the Model
from sklearn.neural_network import MLPClassifier

# Creating a Multi-Layer Perceptron (MLP) classifier
# with a hidden layer structure of (10, 5) and a maximum of 1000 iterations
mlp = MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000)

# Fitting the training data to our model
mlp.fit(train_data, train_labels)


MLPClassifier(hidden_layer_sizes=(10, 5), max_iter=1000)

In [ ]:
from sklearn.metrics import accuracy_score

# Making predictions on the training data
predictions_train = mlp.predict(train_data)
# Calculating and printing the accuracy on the training data
print(accuracy_score(predictions_train, train_labels))

# Making predictions on the test data
predictions_test = mlp.predict(test_data)
# Calculating and printing the accuracy on the test data
print(accuracy_score(predictions_test, test_labels))

0.9833333333333333
0.9333333333333333


In [ ]:
from sklearn.metrics import confusion_matrix

# Generating the confusion matrix for the training data
conf_matrix_train = confusion_matrix(predictions_train, train_labels)
print("Confusion Matrix for Training Data:")
print(conf_matrix_train)

Confusion Matrix for Training Data:
[[42  0  0]
 [ 0 37  1]
 [ 0  1 39]]


In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.datasets import load_iris
import numpy as np

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Encode target labels using one-hot encoding
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = keras.utils.to_categorical(y, num_classes=3)

# Split the dataset into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the dataset to improve model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the neural network model
model = keras.Sequential([
    layers.Dense(10, activation='relu', input_shape=(X_train.shape[1],)),  # First hidden layer with ReLU activation
    layers.Dense(8, activation='relu'),  # Second hidden layer with ReLU activation
    layers.Dense(3, activation='softmax')  # Output layer with softmax activation for multi-class classification
])

# Compile the model using Adam optimizer and categorical cross-entropy loss function
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model using training data with validation on test data
model.fit(X_train, y_train, epochs=100, batch_size=5, validation_data=(X_test, y_test))

# Evaluate the model on test data
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")


Epoch 1/100


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.0850 - loss: 1.2541 - val_accuracy: 0.2000 - val_loss: 1.1978
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1628 - loss: 1.2036 - val_accuracy: 0.3000 - val_loss: 1.0773
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2967 - loss: 1.0892 - val_accuracy: 0.4333 - val_loss: 0.9823
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4531 - loss: 1.0217 - val_accuracy: 0.7000 - val_loss: 0.9039
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5467 - loss: 0.9402 - val_accuracy: 0.7333 - val_loss: 0.8301
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6468 - loss: 0.8559 - val_accuracy: 0.6667 - val_loss: 0.7538
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7170 - loss: 0.7555 - val_accuracy: 0.7333 - val_loss: 0.6915
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6634 - loss: 0.7247 - val_accuracy: 0.7000 - val_loss: 0.